# Generated by Django 4.2.11 on 2026-02-16 16:03

import uuid

import django.db.models.deletion
from django.db import migrations, models

import genericissuetracker.models.attachment


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier for this record.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag. True means logically deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the record was soft deleted.', null=True)),
                ('name', models.CharField(help_text='Human-readable label name.', max_length=50)),
                ('slug', models.SlugField(help_text='Unique machine-friendly identifier for this label.', max_length=60, unique=True)),
                ('color', models.CharField(default='#6B7280', help_text='HEX color code (e.g. #FF5733). Validation handled in serializers.', max_length=7)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='genericissu_slug_452dc5_idx'), models.Index(fields=['name'], name='genericissu_name_c3971e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier for this record.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag. True means logically deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the record was soft deleted.', null=True)),
                ('title', models.CharField(help_text='Short descriptive title of the issue.', max_length=255)),
                ('description', models.TextField(help_text='Detailed explanation of the issue in markdown or plain text.')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', help_text='Current lifecycle state of the issue.', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, default='MEDIUM', help_text='Severity level of the issue.', max_length=20)),
                ('reporter_email', models.EmailField(help_text='Email address of the issue reporter.', max_length=254)),
                ('reporter_user_id', models.IntegerField(blank=True, db_index=True, help_text='Optional user ID from host application identity system.', null=True)),
                ('is_public', models.BooleanField(db_index=True, default=True, help_text='If False, issue is restricted to internal viewers.')),
                ('labels', models.ManyToManyField(blank=True, help_text='Categorization labels assigned to this issue.', related_name='issues', to='genericissuetracker.label')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IssueComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier for this record.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag. True means logically deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the record was soft deleted.', null=True)),
                ('body', models.TextField(help_text='Comment content in markdown or plain text.')),
                ('commenter_email', models.EmailField(help_text='Email address of the commenter.', max_length=254)),
                ('commenter_user_id', models.IntegerField(blank=True, db_index=True, help_text='Optional user ID from host application identity system.', null=True)),
                ('issue', models.ForeignKey(help_text='The issue this comment belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='genericissuetracker.issue')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['issue'], name='genericissu_issue_i_be1747_idx'), models.Index(fields=['created_at'], name='genericissu_created_a68090_idx'), models.Index(fields=['commenter_user_id'], name='genericissu_comment_7d0c58_idx')],
            },
        ),
        migrations.CreateModel(
            name='IssueAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier for this record.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag. True means logically deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the record was soft deleted.', null=True)),
                ('file', models.FileField(help_text='Uploaded file.', upload_to=genericissuetracker.models.attachment.issue_attachment_upload_path)),
                ('original_name', models.CharField(help_text='Original filename at upload time.', max_length=255)),
                ('size', models.PositiveBigIntegerField(help_text='File size in bytes.')),
                ('issue', models.ForeignKey(help_text='Issue this attachment belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='genericissuetracker.issue')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['issue'], name='genericissu_issue_i_d08f93_idx'), models.Index(fields=['created_at'], name='genericissu_created_2cb6ce_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['status'], name='genericissu_status_e78d95_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['priority'], name='genericissu_priorit_c418dd_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['created_at'], name='genericissu_created_76788d_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['reporter_user_id'], name='genericissu_reporte_5d2217_idx'),
        ),
    ]
