# Generated by Django 4.2.11 on 2026-02-21 12:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('genericissuetracker', '0002_issue_issue_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issue_number',
            field=models.BigIntegerField(db_index=True, editable=False, help_text='Sequential human-friendly identifier for this issue.', unique=True),
        ),
        migrations.CreateModel(
            name='IssueStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier for this record.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag. True means logically deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the record was soft deleted.', null=True)),
                ('old_status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], max_length=20)),
                ('new_status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], max_length=20)),
                ('changed_by_user_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('changed_by_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='genericissuetracker.issue')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['issue'], name='genericissu_issue_i_7100d6_idx'), models.Index(fields=['created_at'], name='genericissu_created_a44768_idx')],
            },
        ),
    ]
