# Generated by Django 4.2.11 on 2026-03-01 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genericissuetracker', '0003_alter_issue_issue_number_issuestatushistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='issueattachment',
            name='number',
            field=models.BigIntegerField(db_index=True, editable=False, help_text='Sequential human-friendly identifier.', null=True),
        ),
        migrations.AddField(
            model_name='issuecomment',
            name='number',
            field=models.BigIntegerField(db_index=True, editable=False, help_text='Sequential human-friendly identifier.', null=True),
        ),
        migrations.AddField(
            model_name='label',
            name='number',
            field=models.BigIntegerField(db_index=True, editable=False, help_text='Sequential human-friendly identifier.', null=True),
        ),
        migrations.AlterField(
            model_name='issuecomment',
            name='body',
            field=models.TextField(help_text='Comment content in markdown or plain text.', max_length=10000),
        ),
    ]
