# Generated by Django 4.2.11 on 2026-03-01 07:06
from django.db import migrations


def backfill_comment_numbers(apps, schema_editor):
    IssueComment = apps.get_model("genericissuetracker", "IssueComment")

    for index, obj in enumerate(
        IssueComment.objects.order_by("created_at"), start=1
    ):
        obj.number = index
        obj.save(update_fields=["number"])


def backfill_attachment_numbers(apps, schema_editor):
    IssueAttachment = apps.get_model("genericissuetracker", "IssueAttachment")

    for index, obj in enumerate(
        IssueAttachment.objects.order_by("created_at"), start=1
    ):
        obj.number = index
        obj.save(update_fields=["number"])


def backfill_label_numbers(apps, schema_editor):
    Label = apps.get_model("genericissuetracker", "Label")

    for index, obj in enumerate(
        Label.objects.order_by("created_at"), start=1
    ):
        obj.number = index
        obj.save(update_fields=["number"])


class Migration(migrations.Migration):

    dependencies = [
        ("genericissuetracker", "0004_issueattachment_number_issuecomment_number_and_more"),
    ]

    operations = [
        migrations.RunPython(backfill_comment_numbers),
        migrations.RunPython(backfill_attachment_numbers),
        migrations.RunPython(backfill_label_numbers),
    ]
