# Generated by Django 4.2.11 on 2026-03-01 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genericissuetracker', '0005_backfill_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issueattachment',
            name='number',
            field=models.BigIntegerField(db_index=True, editable=False, help_text='Sequential human-friendly identifier for this attachment.', unique=True),
        ),
        migrations.AlterField(
            model_name='issuecomment',
            name='number',
            field=models.BigIntegerField(db_index=True, editable=False, help_text='Sequential human-friendly identifier for this comment.', unique=True),
        ),
        migrations.AlterField(
            model_name='label',
            name='number',
            field=models.BigIntegerField(db_index=True, editable=False, help_text='Sequential human-friendly identifier for this label.', unique=True),
        ),
    ]
