# Generated by Django 4.2.11 on 2026-03-02 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genericissuetracker', '0006_alter_issueattachment_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issueattachment',
            name='comment',
            field=models.ForeignKey(blank=True, help_text='Optional comment this attachment belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='genericissuetracker.issuecomment'),
        ),
        migrations.AddField(
            model_name='issueattachment',
            name='uploaded_by_email',
            field=models.EmailField(blank=True, help_text='Email address of the uploader.', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='issueattachment',
            name='uploaded_by_user_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='Optional user ID from host application identity system.', null=True),
        ),
        migrations.AddIndex(
            model_name='issueattachment',
            index=models.Index(fields=['comment'], name='genericissu_comment_41afed_idx'),
        ),
        migrations.AddIndex(
            model_name='issueattachment',
            index=models.Index(fields=['uploaded_by_user_id'], name='genericissu_uploade_a194bf_idx'),
        ),
    ]
