# Generated by Django 4.2.11 on 2026-03-02 02:21

from django.db import migrations


def backfill_uploaded_by_email(apps, schema_editor):
    IssueAttachment = apps.get_model(
        "genericissuetracker", "IssueAttachment"
    )

    for attachment in IssueAttachment.objects.filter(uploaded_by_email__isnull=True):
        issue = attachment.issue
        attachment.uploaded_by_email = issue.reporter_email
        attachment.uploaded_by_user_id = issue.reporter_user_id
        attachment.save(update_fields=["uploaded_by_email", "uploaded_by_user_id"])


class Migration(migrations.Migration):

    dependencies = [
        ('genericissuetracker', '0007_issueattachment_comment_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_uploaded_by_email, migrations.RunPython.noop),
    ]