# Generated by Django 4.2.11 on 2026-03-02 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genericissuetracker', '0008_backfill_uploaded_by_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issueattachment',
            name='uploaded_by_email',
            field=models.EmailField(help_text='Email address of the uploader.', max_length=254),
        ),
    ]
