# Generated by Django 4.2.11 on 2026-03-06 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genericissuetracker', '0009_alter_issueattachment_uploaded_by_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuestatushistory',
            name='event_type',
            field=models.CharField(db_index=True, default='status_changed', help_text='Machine readable event classification.', max_length=32),
        ),
        migrations.AddField(
            model_name='issuestatushistory',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Optional structured metadata for integrations and automation.', null=True),
        ),
        migrations.AddIndex(
            model_name='issuestatushistory',
            index=models.Index(fields=['issue', 'created_at'], name='genericissu_issue_i_fb07c3_idx'),
        ),
    ]
